### ISSUE TITLE
How to handle the notes

### ISSUE THREAD

**Issue by davidhsonic** [monmouth-college-cs/sddc-reading-notes-monmouth-college-comp-335#1]
I think we should split the work into two jobs:
1. Summarizing the chapter sections and coming up with names for the sections (if they don't already have ones)
2. Coming up with review questions and references

And then we should split each chapter into three parts (groups of sections) and assign each person one of the jobs for one of the parts (as in, one person would always do the review questions and references for the second part of each chapter).

The outlines would be easy to make with the names we came up with for the chapter sections.

**Comment by davidhsonic** [comment]
Also, I refuse to do any summaries. Making the summary for the interview was an awful experience.

**Comment by Shayno527** [comment]
I agree with David. If we did it in a format similar to that, I think it would be very well organized and easy to read/navigate. Or if everyone would rather take a divide and conquer approach where we each do a portion of the notes. Each of our work could then be sequential and could be easily combined together.

**Comment by jlmayfield** [comment]
I'll throw out an idea that you all can take or leave as you want. It's just a starting place:
1. Everyone do your own notes however you'd like and push them as a branch to the repository.
2. Choose someone for each set of notes to collect all the individual notes and collate them. Then issue a PR on a first draft.
3. Everyone reviews the PR, makes suggestions in the issue.  
4. The original submitter makes edits.  Someone else reviews and merges. 

The key is using branches to do/share individual work.

**Comment by jlmayfield** [comment]
@davidhsonic I think chapter summaries will be much easier. A chapter is focused and has an overall goal. The interviews are a bit all over the place.

**Comment by davidhsonic** [comment]
I figured out a way to make the notes easier to read: https://davidhsonic.github.io/test.html (click the links and the checkboxes)

The issues with my idea are that it requires JavaScript and markdown viewers don't normally support JavaScript (I think), and that it would require adding html tags to the notes.

Also, the notes would all need to be in one file, but I don't see that being an issue with how easy to read they would be.
