### ISSUE TITLE
How to add assignees, labels, due dates?

### ISSUE THREAD

**Issue by LukasNilsson** [monmouth-college-cs/sddc-reading-notes-monmouth-college-comp-335#10]
@jlmayfield - I am not able to do it when creating issues. Do I not have authority?

**Comment by jlmayfield** [comment]
You should have the needed permissions.  On the right side you should see Assignees and labels. Issues don't have deadlines but I believe Milestones do. You can create them under the issues tab.

**Comment by jlmayfield** [comment]
@LukasNilsson For some reason you weren't on the team for this repository. My guess is you joined the assignment without picking the existing team or something.  It's a public repo, so you can make issues,etc but as you found out, can't assign things, etc.  I added you to the team. Let me know if you see all the assignees, labels, etc.

**Comment by LukasNilsson** [comment]
Fixed, I now see them all
