### ISSUE TITLE
We are definitely not all on the same page as to how we're handling the notes

### ISSUE THREAD

**Issue by davidhsonic** [monmouth-college-cs/sddc-reading-notes-monmouth-college-comp-335#16]
I think we need to all meet in person to discuss what we're each doing when it comes to the notes. At least before we start on the next batch.

**Comment by davidhsonic** [comment]
Probably also a good idea to include Prof. Mayfield in our meeting if possible to get an understanding of how much work he expects each of us to put in.

**Comment by jlmayfield** [comment]
@monmouth-college-cs/monmouth-college-comp-335 We'll start class on 9/10 with a meeting to discuss team communication and teamwork generally. **Maybe show up to class on time?**

**Comment by davidhsonic** [comment]
@monmouth-college-cs/monmouth-college-comp-335 I think it would be helpful if everyone looked at the [notes](https://monmouth-college-cs.github.io/sddc-reading-notes-monmouth-college-comp-335/) before tomorrow.
