### ISSUE TITLE
Summary of summaries file separate file?

### ISSUE THREAD

**Issue by phein** [monmouth-college-cs/sddc-reading-notes-monmouth-college-comp-335#27]
Are we doing summary of summaries in separate file from our branch and pull request to Chapter3 branch?

**Comment by davidhsonic** [comment]
I was thinking we should add our summaries of summaries to the files we already pushed and then pull request the new versions of those files.

**Comment by LukasNilsson** [comment]
I would like to have a seperate .md file in the same branch and just push it as well. Unless there is reason not to do it this way, I'd prefer having the summaries of summaries separate

**Comment by davidhsonic** [comment]
Actually, now that I think about it, separate files would probably be better.
