### ISSUE TITLE
Schedule and organisation

### ISSUE THREAD

**Issue by LukasNilsson** [monmouth-college-cs/sddc-reading-notes-monmouth-college-comp-335#3]
##Chapter 1 and 2:

**Summary:** 
Anthony: Chapter 1 Summary + start of chapter 2 Summary (pg 1-4 + 7-10)
Shane: Middle of chapter 2 Summary (11-19)
Abhi: End of chapter 2 Summary + conclusion (pg 19-26)
//If you think the page numbers should change add a comment

**Review questions and references.** 
Pyae (Chapter 1 RQ + R)
David (Chapter 2 RQ + R)
Lukas (Chapter 2 RQ + R)

**Due dates:** 
//Try to get your work done as early as possible, wednesday at the latest. 

Monday: Read
Tuesday: Read
Wednesday: Summary + review Questions +References Due (Don't forget page numbers)
Thursday: Merging + Bug fix 
Friday: Deadline

**Comment by phein** [comment]
references mean page numbers?

**Comment by LukasNilsson** [comment]
I don't believe so. I think they are references to other sources/papers mentioned in the chapter but not sure. Can someone confirm?

**Comment by davidhsonic** [comment]
I got that the references were to bits in the reading that we'd want to look at again later.
