### ISSUE TITLE
Vote on Summary of Summaries

### ISSUE THREAD

**Issue by Shayno527** [monmouth-college-cs/sddc-reading-notes-monmouth-college-comp-335#32]
Read through everyone's SoS, and comment on your top 2. Try to have this in as soon as possible.

**Comment by AbhiJohal** [comment]
Abhi
David

**Comment by phein** [comment]
David
Abhi

**Comment by Shayno527** [comment]
I think that @davidhsonic and @phein notes are sufficient.
 1. David
 2. Pyae

**Comment by davidhsonic** [comment]
David
Pyae

**Comment by LukasNilsson** [comment]
David
Abhi

**Comment by Awallace8074** [comment]
David
Pyea
