### ISSUE TITLE
Problems with PR

### ISSUE THREAD

**Issue by AbhiJohal** [monmouth-college-cs/sddc-reading-notes-monmouth-college-comp-335#42]
I branched off from the EmptyBranch but now it wouldn't let me make a PR to it. My branch has been published though, so you guys can still review it.

**Comment by Shayno527** [comment]
@AbhiJohal Looks good to me for whenever you get the PR to work.

**Comment by davidhsonic** [comment]
The first sentence of the "But do you like writing?" section is awkwardly worded.

The "Outline of a Functional Specification" section has Outline where it should have Overview.

The "Author's Name" section should probably mention that the functional specification needs to be done by only one person. It implies that already, but it should probably say it directly.
