### ISSUE TITLE
Vote on Summary of Summaries

### ISSUE THREAD

**Issue by Shayno527** [monmouth-college-cs/sddc-reading-notes-monmouth-college-comp-335#46]
Similar to last time, vote on your top 2 Summary of Summaries. Try to have this in as soon as possible!

**Comment by LukasNilsson** [comment]
David’s as it’s the only sos in the chapter 4 branch

**Comment by Shayno527** [comment]
Can you add your SoS submissions and merge them into the Chapter4 branch? @AbhiJohal @Awallace8074

**Comment by AbhiJohal** [comment]
I was trying to do just that. My stuff would end up in the EmptyBranch all the time. I think it's fine now. Please let me know if there are any problems.
@Shayno527

**Comment by phein** [comment]
David and Shayne

**Comment by AbhiJohal** [comment]
I forgot to vote lol 
Shayne and David

**Comment by Awallace8074** [comment]
Shayne and Abhi

**Comment by Shayno527** [comment]
David and Ahbi

**Comment by Shayno527** [comment]
David and Abhi

**Comment by davidhsonic** [comment]
David and Abhi
