### ISSUE TITLE
Chapter 18 Notes?

### ISSUE THREAD

**Issue by LukasNilsson** [monmouth-college-cs/sddc-reading-notes-monmouth-college-comp-335#53]
Shane has uploaded questions and Pyae has uploaded his summary. 

In the google docs I have seen that we wanted to pull notes before break but I'm assuming this is not the case. Maybe end of break? 

Does anyone know which part of the chapter I (Lukas) am responsible for? 

When are we trying to have everyones pull requests in by?

Are we going to update the Excel/Sheets doc?

**Comment by AbhiJohal** [comment]
Go to the Spolsky's chart that we made. There is a new sheet in it, called chapter 18. It has the info for the tasks assigned to you. 
I am also confused about the timeline for the pull requests but I'll be trying to get mine in by tonight.
